DOMAIN = "aqua_medic_dc_runner"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_APP_ID = "app_id"
CONF_TOKEN = "token"
CONF_UID = "uid"
API_BASE_URL = "http://euapi.gizwits.com"
DEFAULT_APP_ID = "07452c4f036a4be3acedf8dbeef38320"  # ✅ Updated app ID from mobile app traffic
DEFAULT_UPDATE_INTERVAL = 30
